services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${USER_UID}
      - PGID=${USER_GID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/deluge/app:/config
      - /home/deluge/storage:/downloads
    ports:
      - "${IP_APPR:-0.0.0.0}:8112:8112"
      - "${IP_APPR:-0.0.0.0}:6881:6881"
      - "${IP_APPR:-0.0.0.0}:6881:6881/udp"
      - "${IP_APPR:-0.0.0.0}:58846:58846" #optional
    restart: unless-stopped